services:
  # api:
  #   build: .
  #   ports:
  #     - "5000:5000"

  maindb:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: empomio_user # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: empomio_password # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: empomio # The PostgreSQL default database (automatically created at first launch)
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
